#ifndef SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H
#define SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H

namespace airball {

enum TelemetryIds {
  AIRDATA_ALPHA = 0x01,
  AIRDATA_BETA = 0x02,
  AIRDATA_Q = 0x03,
  AIRDATA_P = 0x04,
  AIRDATA_T = 0x05,

  SETTINGS_REQUEST = 0x10,

  SETTINGS_SPEED_UNITS = 0x11,
  SETTINGS_IAS_FULL_SCALE = 0x12,
  SETTINGS_V_R = 0x13,
  SETTINGS_V_FE = 0x14,
  SETTINGS_V_NO = 0x15,
  SETTINGS_V_NE = 0x16,
  SETTINGS_ALPHA_STALL = 0x17,
  SETTINGS_ALPHA_STALL_WARNING = 0x18,
  SETTINGS_ALPHA_MIN = 0x19,
  SETTINGS_ALPHA_MAX = 0x1a,
  SETTINGS_ALPHA_X = 0x1b,
  SETTINGS_ALPHA_Y = 0x1c,
  SETTINGS_ALPHA_REF = 0x1d,
  SETTINGS_BETA_FULL_SCALE = 0x1e,
  SETTINGS_BETA_BIAS = 0x1f,
  SETTINGS_BARO_SETTING = 0x20,
  SETTINGS_BALL_TIME_CONSTANT = 0x21,
  SETTINGS_VSI_TIME_CONSTANT = 0x22,
  SETTINGS_SCREEN_WIDTH = 0x23,
  SETTINGS_SCREEN_HEIGHT = 0x24,
  SETTINGS_SHOW_ALTIMETER = 0x25,
  SETTINGS_SHOW_LINK_STATUS = 0x26,
  SETTINGS_SHOW_PROBE_BATTERY_STATUS = 0x27,
  SETTINGS_DECLUTTER = 0x28,
  SETTINGS_SOUND_SCHEME = 0x29,
  SETTINGS_AUDIO_VOLUME = 0x2a,
  SETTINGS_ROTATE_SCREEN = 0x2b,
  SETTINGS_SCREEN_BRIGHTNESS = 0x2c,
  SETTINGS_SHOW_NUMERIC_AIRSPEED = 0x2d,
  SETTINGS_Q_CORRECTION_FACTOR = 0x2e,
};

} // namespace airball

#endif // SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H
