#ifndef SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H
#define SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H

namespace airball {

enum TelemetryIds {
  AIRDATA_ALPHA = 0x001,
  AIRDATA_BETA = 0x002,
  AIRDATA_Q = 0x003,
  AIRDATA_P = 0x004,
  AIRDATA_T = 0x005,

  SETTINGS_REQUEST = 0x010,

  SETTINGS_SPEED_UNITS = 0x011,
  SETTINGS_IAS_FULL_SCALE = 0x012,
  SETTINGS_V_R = 0x013,
  SETTINGS_V_FE = 0x014,
  SETTINGS_V_NO = 0x015,
  SETTINGS_V_NE = 0x016,
  SETTINGS_ALPHA_STALL = 0x017,
  SETTINGS_ALPHA_STALL_WARNING = 0x018,
  SETTINGS_ALPHA_MIN = 0x019,
  SETTINGS_ALPHA_MAX = 0x01a,
  SETTINGS_ALPHA_X = 0x01b,
  SETTINGS_ALPHA_Y = 0x01c,
  SETTINGS_ALPHA_REF = 0x01d,
  SETTINGS_BETA_FULL_SCALE = 0x01e,
  SETTINGS_BETA_BIAS = 0x01f,
  SETTINGS_BARO_SETTING = 0x020,
  SETTINGS_BALL_TIME_CONSTANT = 0x021,
  SETTINGS_VSI_TIME_CONSTANT = 0x022,
  SETTINGS_SCREEN_WIDTH = 0x023,
  SETTINGS_SCREEN_HEIGHT = 0x024,
  SETTINGS_SHOW_ALTIMETER = 0x025,
  SETTINGS_SHOW_LINK_STATUS = 0x026,
  SETTINGS_SHOW_PROBE_BATTERY_STATUS = 0x027,
  SETTINGS_DECLUTTER = 0x028,
  SETTINGS_SOUND_SCHEME = 0x029,
  SETTINGS_AUDIO_VOLUME = 0x02a,
  SETTINGS_ROTATE_SCREEN = 0x02b,
  SETTINGS_SCREEN_BRIGHTNESS = 0x02c,
  SETTINGS_SHOW_NUMERIC_AIRSPEED = 0x02d,
  SETTINGS_Q_CORRECTION_FACTOR = 0x02e,
};

} // namespace airball

#endif // SRC_AIRBALL_MODEL_TELEMETRY_TELEMETRYIDS_H
